### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by rimo030** [Resupath/backend#24]
##  Nestia sdk npm 배포 자동화
main 브랜치에 액션이 일어난 경우. nestia sdk를 npm에 배포합니다.

- [배포된 패키지 보러가기](https://www.npmjs.com/package/@rimo030/resupath-backend)
- [배포 기록 보러가기(Github Action)](https://github.com/Resupath/backend/actions)
- [배포 설정 보러가기](https://github.com/Resupath/backend/issues/24#issuecomment-2565541734)

- **다운로드 명령어  ⚡️**
```sh 
npm i @rimo030/resupath-backend
```

### 1. npm Access Token 발급 받기
1. [npm](https://www.npmjs.com/) 홈페이지에 접속후 프로필을 클릭합니다. `Access Tokens` 메뉴로 들어갑니다.
<img width="1650" alt="image" src="https://github.com/user-attachments/assets/0a30a1d3-76dd-4f10-8c5f-e9e1745688bb" />

2. `Generate New Token` > `Classic Token`을 선택, Publish 타입으로 토큰을 생성합니다.
![image](https://github.com/user-attachments/assets/46ca8161-ad07-4742-a2f1-c90d3bee3e6b)

3.  Publish 타입으로 토큰을 생성합니다.
<img width="1522" alt="image" src="https://github.com/user-attachments/assets/635747d2-595c-4a89-b933-cb794a02c0a6" />

**Comment by rimo030** [comment]
### 2. GitHub Secrets에 토큰 추가
1. GitHub에서 프로젝트의 `Settings > Secrets and variables > Actions`로 이동합니다.

<img width="1720" alt="image" src="https://github.com/user-attachments/assets/dd689905-0233-48db-b20b-88bed8a2beb5" />


2. `New repository secret` 버튼을 클릭하고 아래 정보를 입력합니다.

  - Name: NPM_TOKEN (이름은 꼭 NPM_TOKEN으로 설정)
  - Value: 발급한 npm 토큰 값
 
<img width="1722" alt="image" src="https://github.com/user-attachments/assets/a1f03998-2bda-46ee-a240-06354a977a4a" />



3. Add secret 클릭으로 저장합니다.

![image](https://github.com/user-attachments/assets/9eff053c-e7a4-4209-99af-cc79de5ff803)

**Comment by rimo030** [comment]
### 3. Workflow 파일 생성

- [이 프로젝트의 yml 파일 보기](https://github.com/Resupath/backend/blob/main/.github/workflows/npm-publish.yml)

1. 로컬 프로젝트 디렉토리에서 `.github/workflows` 폴더를 생성한다.

```bash
mkdir -p .github/workflows
```

2. 워크플로 파일 `npm-publish.yml`을 생성합니다.

``` bash
touch .github/workflows/npm-publish.yml
```

3. 파일에 아래 코드를 추가합니다. (주석이 포함되어있습니다.)
```yml
name: Publish to npm  # 워크플로우의 이름

on:
  push:
    branches:
      - main  # 'main' 브랜치에 push가 발생할때 이 워크플로우가 트리거된다.

permissions:
  contents: write  # GitHub 액션이 레포지토리의 콘텐츠를 수정할 수 있도록 쓰기 권한을 부여한다. (버전 커밋을 남기기 위함)

jobs:
  publish:
    runs-on: ubuntu-latest  # lts Ubuntu 환경에서 작업을 실행한다.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 레포지토리의 최신 버전을 클론하여 액션 내에서 사용할 수 있게 한다.

      - name: Use Node.js
        uses: actions/setup-node@v3  # Node.js 환경을 설정.
        with:
          node-version: '21.7.3'  # 사용하려는 Node.js의 버전을 명시.
          registry-url: 'https://registry.npmjs.org/'  # npm 패키지 레지스트리의 URL을 설정. (기본값은 npmjs.org)

      - name: Install dependencies
        run: npm ci  # 의존성 설치를 수행.
        # 'npm ci'는 'npm install'과 다르게 package-lock.json 파일을 정확히 일치시켜 설치한다.

      - name: Update version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")  # package.json 파일에서 현재 버전을 읽어온다.
          NEW_VERSION=$(npm version patch -m "Update version to %s")  # 'npm version patch' 명령어를 사용하여 버전을 패치한다.
          echo "Updated version from $CURRENT_VERSION to $NEW_VERSION"  # 업데이트된 버전을 콘솔에 출력
        working-directory: packages/api  # 실행 디렉토리를 packages/api로 지정

      - name: Commit
        run: |
          git config --global user.name 'GitHub Actions'  # GitHub Actions 자동 커밋시 사용될 사용자명을 설정.
          git config --global user.email 'actions@github.com'  # GitHub Actions 자동 커밋히 사용할 이메일을 설정.
          git add package.json package-lock.json  # package.json과 package-lock.json 파일을 Git 스테이징 영역에 추가
          git commit -m "Update version to $(node -p "require('./package.json').version")"  # 커밋 메시지에 새 버전을 포함하여 커밋.
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main  # GitHub Token을 사용하여 원격 레포지토리에 push.
        working-directory: packages/api  

      - name: Build project
        run: npm run build  # 프로젝트를 빌드합니다. 빌드 명령은 package.json에 정의된 'build' 스크립트를 실행합니다.
        working-directory: packages/api

      - name: Publish to npm
        run: npm run deploy  # 패키지를 npm에 배포합니다. (Nestia 배포 명령어 사용)
        working-directory: packages/api 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # npm 인증 토큰을 환경 변수로 세팅. (1,2 번에서 설정됨)


```
